import { type Metadata } from "next";
import {
	ClerkProvider,
	// CreateOrganization,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";
import { MainLogo } from "@/components/MainLogo";
import ConfirmDialog from "@/components/ConfirmDialog";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Clerk Next.js Quickstart",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			appearance={{
				baseTheme: dark,
			}}
		>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} grid h-screen w-full grid-rows-[auto_1fr_auto] bg-gray-100 antialiased`}
				>
					<header className="flex h-16 items-center justify-between gap-4 p-4">
						<MainLogo />
						<div className="flex items-center gap-4">
							<SignedOut>
								<SignInButton />
								<SignUpButton />
							</SignedOut>
							<SignedIn>
								<UserButton />
							</SignedIn>
						</div>
					</header>
					{/* <SignedIn>
            <CreateOrganization />
          </SignedIn> */}
					<main className="overflow-hidden bg-white">{children}</main>
					<footer className="justify-left flex h-6 items-center px-4">
						<p>2025 © EasyDataSheets.com</p>
					</footer>
					<Toaster />
					<ConfirmDialog />
				</body>
			</html>
		</ClerkProvider>
	);
}
