import { type Metadata } from 'next'
import {
  ClerkProvider,
  // CreateOrganization,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { dark } from '@clerk/themes'
import { Toaster } from "@/components/ui/sonner"
import { MainLogo } from '@/components/MainLogo'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 grid grid-rows-[auto_1fr_auto] w-full h-screen`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 ">
            <MainLogo />
            <div className="flex items-center gap-4">
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {/* <SignedIn>
            <CreateOrganization />
          </SignedIn> */}
          <main className="bg-white">
            {children}
          </main>
          <footer className="flex justify-left items-center px-4 h-6">
            <p>2025 © EasyDataSheets.com</p>
          </footer>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}